# This configuration tells Netlify how to deploy your site.
# It is set up to handle a static site that does NOT need a build step.

[build]
  # Setting the build command to an empty string is crucial.
    # It tells Netlify: "Do not run 'npm install' or any other build script."
      command = ""
        
          # This tells Netlify that your website's files (like index.html)
            # are in the main root directory of your project.
              publish = "."

              # This section sets the environment for the build process.
              [build.environment]
                # We are locking the Node.js version to a stable version (18).
                  # This prevents Netlify from using a newer default version that can cause errors.
                    NODE_VERSION = "18"